blank_issues_enabled: true
contact_links:
  - name: Cog Support Server
    url: https://discord.gg/GET4DVk
    about: Check \#support_othercogs and you can find me there for further help / questions!

  - name: Personal Support Server
    url: https://discord.gg/SKEtjnA
    about: Personal discord server, though I have a channel for bot/cog supports if needed.
